### PR TITLE
Upgrade ActionView Instruments to Rails 6

### PR DESCRIPTION
**Pull request by Laykou**
This refers to issue https://github.com/randy-girard/app_perf/issues/46

ActionView has changed in Rails 6 and these changes should make it compatible

### CODE REVIEW

**Comment by guemidiborhane** [comment]
Can you please merge

**Comment by randy-girard** [comment]
Would this cause Rails < 6 issues?

**Comment by guemidiborhane** [comment]
@randy-girard probably due to the change of API, maybe you can merge to a different branch.

**Comment by randy-girard** [comment]
Probably need to throw in a `if defined?(Rails) && Rails.version >= '6.0.0'` block and put the specific in there. I need to refactor this code out to make it cleaner. Also, you could probably just copy this file and override it in your project for the time being with the specific code you need.

**Comment by guemidiborhane** [comment]
I did something more elegant than that (in case someone needs it) i set the
github url in my Gemfile to point to the patch-1 branch

**Comment by Laykou** [comment]
@randy-girard Can you please refactor it or if you know also of other parts of this gem that are incompatible with Rails 6 it would be highly appreciated if you could input your insight. Thank you very much!

**Comment by randy-girard** [comment]
Yes, I will work on this as soon as I get a chance. Holidays have been hectic. :)

**Comment by Laykou** [comment]
How is this going?

**Comment by randy-girard** [comment]
I have been slowly working on this as I find time, but not quite there yet unfortunately.

**Comment by randy-girard** [comment]
Closing this in favor of https://github.com/randy-girard/app_perf_rpm/pull/27. Still have some work to do on the tests. Getting closer.

**Pull request closed without merging**
